name: Get new videos

on:
    workflow_dispatch:
    schedule:
        - cron: "00 9 * * *"

permissions:
  contents: write

env:
  NOTIFY_CHAT_ID: ${{ secrets.NBA_CHAT_ID }}
  NOTIFY_TOKEN: ${{ secrets.NBA_TOKEN }}

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install package
              run: |-
                  pip install git+https://github.com/HeySlava/youtube-notify.git
            - name: Run youtube-notify
              run: youtube-notify
            - name: Commit and push if changed
              run: |
                  git config user.name "Automated"
                  git config user.email "actions@users.noreply.github.com"
                  timestamp=$(date --rfc-3339=seconds --utc)
                  git add -u
                  git commit -m "top-plays run: ${timestamp}"
                  git push
